### ISSUE TITLE
'docker build' fails on Linux Jenkins slave with jenkins 1.590

### ISSUE THREAD

**Issue by gcarre** [jenkinsci/docker-custom-build-environment-plugin#16] opened 2014-12-18 23:26 UTC
```
Build Docker image from ./docker/Dockerfile ...
[docker] $ docker build -t 53eedae35576ae9544a02443af496a631d838b5b .
FATAL: command execution failed
java.io.IOException: Cannot run program "docker" (in directory "\home\jenkins\jenkins\workspace\gcarre\docker"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1136)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1101)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to amf-docker(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:752)
	at hudson.Launcher$RemoteLauncher.launch(Launcher.java:916)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at com.cloudbees.jenkins.plugins.okidocki.Docker.buildImage(Docker.java:49)
	at com.cloudbees.jenkins.plugins.okidocki.DockerfileImageSelector.prepareDockerImage(DockerfileImageSelector.java:40)
	at com.cloudbees.jenkins.plugins.okidocki.DockerBuildWrapper$2.launch(DockerBuildWrapper.java:68)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:97)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1759)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:803)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1136)
	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1101)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Build step 'Execute shell' marked build as failure
```

**Comment by mohanji** [comment] 2015-05-23 15:14
hi 
i am also facing the below error when i build on jenkins

[workspace] $ docker login -u mohanbmdl -e mohan.bmdl@gmail.com -p ******** https://registry.hub.docker.com/repos/
ERROR: Cannot run program "docker" (in directory "C:\Program Files (x86)\Jenkins\jobs\DockerApp\workspace"): CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "docker" (in directory "C:\Program Files (x86)\Jenkins\jobs\DockerApp\workspace"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:816)
	at hudson.Launcher$ProcStarter.start(Launcher.java:382)
	at com.cloudbees.dockerpublish.DockerBuilder$Perform.executeCmd(DockerBuilder.java:227)
	at com.cloudbees.dockerpublish.DockerBuilder$Perform.maybeLogin(DockerBuilder.java:222)
	at com.cloudbees.dockerpublish.DockerBuilder$Perform.exec(DockerBuilder.java:129)
	at com.cloudbees.dockerpublish.DockerBuilder$Perform.access$100(DockerBuilder.java:110)
	at com.cloudbees.dockerpublish.DockerBuilder.perform(DockerBuilder.java:93)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1744)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 19 more
Build step 'Docker Build and Publish' marked build as failure
Setting commit status on GitHub for https://github.com/mohanji/NewApp/commit/cfd78678a7f7bc3e8abf4adb07c01be0b067a059
Finished: FAILURE

**Comment by ndeloof** [comment] 2015-06-25 07:56
This probably is now fixed with support for docker executable selection from docker-commons

**Closed by ndeloof** 2015-06-25 07:56 UTC
